package com.dr.dao;

import com.dr.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);

    /**
     * 根据userId和productId查询购物车信息
     */
    Cart selectCartByUserIdAndProductId(@Param("userId") Integer userId,
                                        @Param("productId") Integer productId);

    /**
     * 根据userId查询给用户的购物车信息
     * */
    List<Cart> selectCartByUserId(Integer userId);

    /**
     * 删除购物车的某些商品
     * */
    int deleteByUserIdAndProductIds(@Param("userId") Integer userId,
                                    @Param("productIdList") List<Integer> productIdList);
    /**
     * 判断购物车里的商品是否全选
     * */
    int countUnchecked(Integer userId);

    /**
     * 操作购物车商品是否选中
     * */
    int selectOrUnselectProduct(@Param("userId") Integer userId,
                                @Param("productId") Integer productId,
                                @Param("checked") Integer checked);

    /**
     * 对用户购物车进行全选或取消全选操作
     * */
    int selectAllByUserId(@Param("userId") Integer userId,
                          @Param("checked") Integer checked);

    /**
     * 购物车中产品数量
     * */
    int  get_cart_product_count(Integer userId);

    /**
     * 查询购物车中用户已选中的商品
     * */
    List<Cart> findCartListByUserIdAndChecked(@Param("userId") Integer userId,
                                              @Param("checked") Integer checked);
    /**
     * 批量删除购物车中的商品（生成订单的商品）
     * */
    int deleteBatch(List<Cart> cartList);

}