package com.dr.dao;

import com.dr.pojo.UserInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserInfo record);

    /**
     * 校验用户名
     * */
    int checkUsername(String username);

    /**
     * 根据用户民和密码查找用户信息
     * */
    UserInfo selectUserInfoByUsernameAndPassword(@Param("username") String username,
                                                 @Param("password") String password);
    /**
     * 校验邮箱
     * */
    int checkEmail(String email);

    /**
     * 根据用户名查询密保问题
     * */
    String selectQuestionByUsername(String username);

    /**
     * 根据用户名，问题，答案查询记录
     * */
    int selectByUsernameAndQuestionAndAnswer(@Param("username") String username,
                                             @Param("question") String question,
                                             @Param("answer") String answer);

    /**
     * 修改用户密码
     * */
    int updateUserPassword(@Param("username") String username,
                           @Param("password") String newPassword);

    /**
     * 根据旧密码修改为新密码
   * */
    int updatePasswordByPasswordOld(UserInfo userInfo);

    /**
     * 更新用户信息
     * */
    int updateUserBySelectActive(UserInfo userInfo);

}